// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using product_api.Data;

#nullable disable

namespace product_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230506150600_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("product_api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_at = new DateTime(2023, 5, 6, 18, 6, 0, 940, DateTimeKind.Local).AddTicks(9250),
                            Description = "Description",
                            Image_url = "https...",
                            Price = 200f,
                            State = "Draft",
                            Title = "Milk",
                            Updated_at = new DateTime(2023, 5, 6, 18, 6, 0, 940, DateTimeKind.Local).AddTicks(9301)
                        },
                        new
                        {
                            Id = 2,
                            Created_at = new DateTime(2023, 5, 6, 18, 6, 0, 940, DateTimeKind.Local).AddTicks(9303),
                            Description = "Description",
                            Image_url = "https...",
                            Price = 500f,
                            State = "Draft",
                            Title = "Flower",
                            Updated_at = new DateTime(2023, 5, 6, 18, 6, 0, 940, DateTimeKind.Local).AddTicks(9304)
                        },
                        new
                        {
                            Id = 3,
                            Created_at = new DateTime(2023, 5, 6, 18, 6, 0, 940, DateTimeKind.Local).AddTicks(9307),
                            Description = "Description",
                            Image_url = "https...",
                            Price = 100f,
                            State = "Draft",
                            Title = "Fish",
                            Updated_at = new DateTime(2023, 5, 6, 18, 6, 0, 940, DateTimeKind.Local).AddTicks(9308)
                        },
                        new
                        {
                            Id = 4,
                            Created_at = new DateTime(2023, 5, 6, 18, 6, 0, 940, DateTimeKind.Local).AddTicks(9309),
                            Description = "Description",
                            Image_url = "https...",
                            Price = 270f,
                            State = "Draft",
                            Title = "Wood",
                            Updated_at = new DateTime(2023, 5, 6, 18, 6, 0, 940, DateTimeKind.Local).AddTicks(9310)
                        });
                });

            modelBuilder.Entity("product_api.Models.User", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Email = "jason.admin@email.com",
                            Name = "jason_admin",
                            Password = "MyPass_w0rd",
                            Role = "Admin"
                        },
                        new
                        {
                            Email = "elyse.seller@email.com",
                            Name = "elyse_manager",
                            Password = "MyPass_w0rd",
                            Role = "Manager"
                        },
                        new
                        {
                            Email = "elyse.customer@email.com",
                            Name = "elyse_customer",
                            Password = "MyPass_w0rd",
                            Role = "Customer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
